version: '2'

services:
  worksonmymachine:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.debug
      args:
      - SERVER_URLS=http://*:80
    ports:
    - "80:80"
    volumes:
    - ..:/app
